server:
  port: 8888
  servlet:
    session:
      cookie:
        http-only: true

spring:
  application:
    name: uaa-service
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  jackson:
    # 输出时间为 时间戳
    #    serialization:
    #      write-dates-as-timestamps: true
    # 输出为指定格式字符串
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  task:
    execution:
      thread-name-prefix: auth-task-
      pool:
        core-size: 4
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: auth-scheduling-
      pool:
        size: 2
  thymeleaf:
    cache: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.berry.uaa.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

uaa:
  key-store:
    name: keystore.jks
    password: berry123
    alias: keystore

management:
  endpoint:
    health:
      show-details: always
